# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_record', '0002_bgmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgmodel',
            name='type',
            field=models.CharField(choices=[('before', '餐前'), ('after', '飯後')], default='after', max_length=10),
        ),
    ]
