# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_record', '0003_bgmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmodel',
            name='type',
            field=models.CharField(choices=[('before', '餐前'), ('after', '飯後')], max_length=10),
        ),
    ]
