# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_record', '0006_auto_20170501_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drugintakemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insulinintakemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
