# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L')], default='mg/dL', max_length=10)),
                ('breakfast_reminder', models.TimeField(default=datetime.time(9, 0))),
                ('breakfast_reminder_status', models.BooleanField(default=True)),
                ('lunch_reminder', models.TimeField(default=datetime.time(12, 30))),
                ('lunch_reminder_status', models.BooleanField(default=True)),
                ('dinner_reminder', models.TimeField(default=datetime.time(7, 30))),
                ('dinner_reminder_status', models.BooleanField(default=True)),
                ('late_reminder', models.TimeField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
