# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userlogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingmodel',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettingmodel',
            name='late_reminder',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettingmodel',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
