# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170321_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingmodel',
            name='late_reminder',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
