# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170321_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingmodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettingmodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
