# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170321_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='breakfast_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='breakfast_reminder_status',
        ),
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='dinner_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='dinner_reminder_status',
        ),
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='lunch_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='lunch_reminder_status',
        ),
    ]
