# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170412_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogmodel',
            name='request_text',
            field=models.CharField(max_length=100, verbose_name='Request from user.'),
        ),
        migrations.AlterField(
            model_name='userlogmodel',
            name='response',
            field=models.CharField(max_length=100, verbose_name='Response from debby.'),
        ),
    ]
