# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('mechanism', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('taboo', models.CharField(max_length=200)),
                ('awareness', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DrugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(max_length=100)),
                ('permission_type', models.CharField(max_length=20)),
                ('main_ingredient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DrugTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('user_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
