# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdetailmodel',
            name='awareness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
