# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_food', '0002_foodmodel_foodnamemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodnamemodel',
            name='foods',
        ),
        migrations.DeleteModel(
            name='FoodModel',
        ),
        migrations.DeleteModel(
            name='FoodNameModel',
        ),
    ]
