# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_food', '0003_auto_20170515_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_number', models.CharField(max_length=20, verbose_name='整合編號')),
                ('food_type', models.CharField(max_length=20, verbose_name='食物分類')),
                ('sample_name', models.CharField(max_length=100, unique=True, verbose_name='樣品名稱')),
                ('modified_calorie', models.FloatField(verbose_name='修正熱量-成分值(kcal)')),
                ('crude_protein', models.FloatField(verbose_name='粗蛋白-成分值(g)')),
                ('crude_fat', models.FloatField(verbose_name='粗脂肪-成分值(g)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='總碳水化合物-成分值(g)')),
                ('dietary_fiber', models.FloatField(blank=True, null=True, verbose_name='膳食纖維-成分值(g)')),
                ('metabolic_carbohydrates', models.FloatField(verbose_name='可代謝醣類(g)')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_as_name', models.CharField(max_length=50, verbose_name='代稱')),
                ('foods', models.ManyToManyField(to='consult_food.FoodModel')),
            ],
        ),
    ]
