# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_food', '0004_foodmodel_foodnamemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodnamemodel',
            name='foods',
        ),
        migrations.AlterField(
            model_name='foodnamemodel',
            name='known_as_name',
            field=models.CharField(max_length=100, verbose_name='代稱'),
        ),
    ]
