# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult_food', '0005_auto_20170516_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnamemodel',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consult_food.FoodModel'),
            preserve_default=False,
        ),
    ]
