# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(9, 0))),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('bg', 'blood sugar'), ('insulin', 'insulin'), ('drug', 'drug')], default=True, max_length=10)),
            ],
        ),
    ]
