# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('bg', '血糖'), ('sports', '運動'), ('diet', '飲食'), ('greeting', '招呼詞'), ('other', '其他')], max_length=20)),
                ('answer', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
