# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20170307_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qamodel',
            name='callback',
            field=models.CharField(choices=[('BGRecord', '紀錄血糖'), ('FoodRecord', '紀錄飲食'), ('FoodQuery', '查詢食物熱量'), ('DrugQuery', '查詢藥物'), ('Chat', '閒聊')], max_length=20),
        ),
    ]
