# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_auto_20170310_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=30)),
                ('callback', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='QAModel',
        ),
    ]
